/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BayarRouteImport } from './routes/bayar'
import { Route as CekRouteImport } from './routes/cek'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as FormRouteImport } from './routes/form'
import { Route as StatusRouteImport } from './routes/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BayarRoute = BayarRouteImport.update({
  id: '/bayar',
  path: '/bayar',
  getParentRoute: () => rootRouteImport,
} as any)
const CekRoute = CekRouteImport.update({
  id: '/cek',
  path: '/cek',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bayar': typeof BayarRoute
  '/cek': typeof CekRoute
  '/daftar': typeof DaftarRoute
  '/form': typeof FormRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bayar': typeof BayarRoute
  '/cek': typeof CekRoute
  '/daftar': typeof DaftarRoute
  '/form': typeof FormRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bayar': typeof BayarRoute
  '/cek': typeof CekRoute
  '/daftar': typeof DaftarRoute
  '/form': typeof FormRoute
  '/status': typeof StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bayar' | '/cek' | '/daftar' | '/form' | '/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bayar' | '/cek' | '/daftar' | '/form' | '/status'
  id: '__root__' | '/' | '/bayar' | '/cek' | '/daftar' | '/form' | '/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BayarRoute: typeof BayarRoute
  CekRoute: typeof CekRoute
  DaftarRoute: typeof DaftarRoute
  FormRoute: typeof FormRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bayar': {
      id: '/bayar'
      path: '/bayar'
      fullPath: '/bayar'
      preLoaderRoute: typeof BayarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek': {
      id: '/cek'
      path: '/cek'
      fullPath: '/cek'
      preLoaderRoute: typeof CekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BayarRoute: BayarRoute,
  CekRoute: CekRoute,
  DaftarRoute: DaftarRoute,
  FormRoute: FormRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
